openapi: 3.0.0
info:
  title: Stock Quotes API
  description: A simple API for getting stock quotes.
  version: 1.0.0
servers:
- url: https://stockquotes.example.com
paths:
  /stocks/{stockName}:
    get:
      summary: Get the quote for a single stock.
      operationId: getQuote
      parameters:
      - name: stockName
        in: path
        required: true
        type: string
      responses:
        '200':
          description: The stock quote.
          content:
            application/json:
              schema:
                type: object
                properties:
                  stockName:
                    type: string
                  currentPrice:
                    type: number
                  changePercent:
                    type: number
                  bidPrice:
                    type: number
                  askPrice:
                    type: number
                  volume:
                    type: number
  /stocks:
    get:
      summary: Get the quotes for a list of stocks.
      operationId: getQuotes
      parameters:
      - name: stockNames
        in: query
        required: true
        type: array
        items:
          type: string
      responses:
        '200':
          description: The stock quotes.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    stockName:
                      type: string
                    currentPrice:
                      type: number
                    changePercent:
                      type: number
                    bidPrice:
                      type: number
                    askPrice:
                      type: number
                    volume:
                      type: number
